version: '2'

services:
  musicstore:
    image: user/musicstore:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
    environment:
      - REMOTE_DEBUGGING